name: build dev version

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the dev version Docker image
      run: docker build . --file Dockerfile --tag ysslang/finedocker:dev_$(date +%s)
