name: Stable Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the stable version Docker image
      run: docker build . --file Dockerfile --tag ysslang/finedocker:test_build_$(date +%s)
